apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: client-next
  name: client-next
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client-next
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: client-next
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://db/mussia8
            - name: PORT
              value: "3340"
          image: eu.gcr.io/mussia8/client-next
          name: client-next
          ports:
            - containerPort: 3340
          resources: {}
      restartPolicy: Always
status: {}
