apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: event2
  name: event2
spec:
  ports:
    - name: "3337"
      port: 3337
      targetPort: 3337
  selector:
    io.kompose.service: event2
status:
  loadBalancer: {}
