apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: go-api
  name: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: go-api
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://db/mussia8
            - name: PORT
              value: "3000"
          image: eu.gcr.io/mussia8/go-api
          name: go-api
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
