version: "3"

services:
  db:
    image: mongo
    ports:
      - 27017:27017
  users-api:
    image: eu.gcr.io/mussia8/users-api
    build:
      context: apps/fullstack/users-api
      dockerfile: Dockerfile
    container_name: users-api
    environment:
      - DB_URL=mongodb://db/mussia8
    ports:
      - 3333:3333
#    command: npm run start
