apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: db1
  name: db1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: db1
    spec:
      containers:
        - image: mongo
          name: db1
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
