name: Pulumi
on:
  push:
#    branches:
#      - main
#    paths:
#      - "apps/big-data/**"
#  pull_request:
#    paths:
#      - "apps/big-data/**"
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mussia8
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: |-
          gcloud --quiet auth configure-docker
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: master-inner
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: app/big-data/infra
#          cwd: app/big-data/infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
